import Head from "next/head";
import { Layout, Menu, Row, Col, Card } from "antd";
import styles from "../styles/Home.module.css";
import ComponentContainer from "../component/ComponentContainer";
import Container from "../component/Container";
import { ItemTypes } from "../component/ItemTypes";

export default function Home() {
  const { Header, Content } = Layout;

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        style={{
          position: "fixed",
          zIndex: 1,
          width: "100%",
        }}
      >
        <div className="logo" />
        <Menu
          theme="dark"
          mode="horizontal"
          defaultSelectedKeys={["2"]}
          items={new Array(1).fill(null).map((_, index) => ({
            key: String(index + 1),
            label: `Exam`,
          }))}
        />
        <Content
          className="site-layout"
          style={{
            padding: "0 50px",
            marginTop: 64,
          }}
        >
          <Row gutter={[16, 0]}>
            <Col md={6} lg={6} xs={24}>
              <div className={styles.card_style}>
                <Card>
                  <p>Tool Section</p>

                  <ComponentContainer
                    name="button"
                    image="/button.png"
                    type={ItemTypes.BUTTON}
                  />

                  <ComponentContainer
                    name="input"
                    image="/input.png"
                    type={ItemTypes.INPUT}
                  />
                  {/* <Image
                    src="/input.png"
                    alt="Vercel Logo"
                   width={120}
                    height={100}
                  /> */}
                </Card>
              </div>
            </Col>
            <Col md={18} lg={18} xs={24}>
              <Card>
                <p>Layout Section</p>
                <Container />
              </Card>
            </Col>
          </Row>
        </Content>
      </Header>
    </Layout>
  );
}
